
const xpath_ENDTOUR = '//*[@id="step-0"]/div[3]/button',
  xpath_WELCOME = '//*[@id="step-0"]/div[3]/div/button[2]',
  xpath_TRANSLATION = '//*[@id="step-1"]/div[3]/div/button[2]',
  xpath_TranslatorKeys = '//*[@id="step-2"]/div[3]/div/button[2]',
  xpath_CreateLanguagePattern = '//*[@id="step-3"]/div[3]/div/button[2]',
  xpath_TranslationPatterns = '//*[@id="step-4"]/div[3]/div/button[2]',
  xpath_BlacklistTab = '//*[@id="step-5"]/div[3]/div/button[2]',
  xpath_BlacklistWebsites = '//*[@id="step-6"]/div[3]/div/button[2]',
  xpath_BlacklistWords = '//*[@id="step-7"]/div[3]/div/button[2]',
  xpath_LearningTab = '//*[@id="step-8"]/div[3]/div/button[2]',
  xpath_SavedTranslationDiv = '//*[@id="step-9"]/div[3]/div/button[2]',
  xpath_LearntWordsDiv = '//*[@id="step-10"]/div[3]/div/button[2]',
  xpath_AdvTab = '//*[@id="step-11"]/div[3]/div/button[2]',
  xpath_BackupTab = '//*[@id="step-12"]/div[3]/div/button[2]',
  xpath_QuizTab = '//*[@id="step-13"]/div[3]/div/button[2]',
  xpath_statsTab = '//*[@id="step-14"]/div[3]/div/button[2]',
  xpath_ContributeTab = '//*[@id="step-15"]/div[3]/div/button[2]',
  xpath_FinalTourEnd = '//*[@id="step-16"]/div[3]/button';

module.exports = {
  endTour: xpath_ENDTOUR,
  nextWelcome: xpath_WELCOME,
  nextTranslation: xpath_TRANSLATION,
  nextTranslatorkeys: xpath_TranslatorKeys,
  nextCreateLP: xpath_CreateLanguagePattern,
  nextTP: xpath_TranslationPatterns,
  nextBlacklistTab: xpath_BlacklistTab,
  nextBW: xpath_BlacklistWebsites,
  nextBWords: xpath_BlacklistWords,
  nextLearningTab: xpath_LearningTab,
  nextSavedTranslationDiv: xpath_SavedTranslationDiv,
  nextLearntWordsDiv: xpath_LearntWordsDiv,
  nextAdv: xpath_AdvTab,
  nextBackUp: xpath_BackupTab,
  nextQuiz: xpath_QuizTab,
  nextStats: xpath_statsTab,
  nextContribute: xpath_ContributeTab,
  nextTourFinish: xpath_FinalTourEnd
};