const yandexInputField = '//*[@id="translator-keys"]/div[2]/div[1]/input',
  azureInputField = '//*[@id="translator-keys"]/div[2]/div[2]/input',
  googleInputField = '//*[@id="translator-keys"]/div[2]/div[3]/input',
  patternTranslator = '//*[@id="translator"]',
  patternPercent = '//*[@id="percentage"]',
  patternSrcLang = '//*[@id="srcLang"]',
  patternTargetLang = '//*[@id="targetLang"]',
  patternCreationDiv = '//*[@id="create-new-pattern"]/div[2]',
  patternCreateButton = '//*[@id="create-new-pattern"]/div[2]/form/button',
  createdYandex = '//*[@id="manage-patterns"]/div[3]/a[1]',
  createdAzure = '//*[@id="manage-patterns"]/div[3]/a[2]',
  createdGoogle = '//*[@id="manage-patterns"]/div[3]/a[3]',
  activeSymbolLastPattern = '//*[@id="manage-patterns"]/div[3]/a[3]/span[1]',
  activeSymbolFirstPattern = '//*[@id="manage-patterns"]/div[3]/a[1]/span[1]',
  createdPatternsDiv = '//*[@id="manage-patterns"]',
  deleteFirstPattern = '//*[@id="manage-patterns"]/div[3]/a[1]/span[7]/button',
  deleteSecondPattern = '//*[@id="manage-patterns"]/div[3]/a[2]/span[6]/button',
  deleteThirdPattern = '//*[@id="manage-patterns"]/div[3]/a[3]/span[6]/button';

module.exports = {
  yandexInputField: yandexInputField,
  azureInputField: azureInputField,
  googleInputField: googleInputField,
  patternTranslator: patternTranslator,
  patternPercent: patternPercent,
  patternSrcLang: patternSrcLang,
  patternTargetLang: patternTargetLang,
  patternCreationDiv: patternCreationDiv,
  patternCreateButton: patternCreateButton,
  createdYandex: createdYandex,
  createdAzure: createdAzure,
  createdGoogle: createdGoogle,
  activeSymbolFirstPattern: activeSymbolFirstPattern,
  activeSymbolLastPattern: activeSymbolLastPattern,
  createdPatternsDiv: createdPatternsDiv,
  deleteFirstPattern: deleteFirstPattern,
  deleteSecondPattern: deleteSecondPattern,
  deleteThirdPattern: deleteThirdPattern,
};
