export var azureLanguages = {
  'Afrikaans': 'af',
  'Arabic': 'ar',
  'Bulgarian': 'bg',
  'Bangla': 'bn',
  'Bosnian': 'bs',
  'Catalan': 'ca',
  'Czech': 'cs',
  'Welsh': 'cy',
  'Danish': 'da',
  'German': 'de',
  'Greek': 'el',
  'English': 'en',
  'Spanish': 'es',
  'Estonian': 'et',
  'Persian': 'fa',
  'Finnish': 'fi',
  'Filipino': 'fil',
  'Fijian': 'fj',
  'French': 'fr',
  'Hebrew': 'he',
  'Hindi': 'hi',
  'Croatian': 'hr',
  'Haitian Creole': 'ht',
  'Hungarian': 'hu',
  'Indonesian': 'id',
  'Icelandic': 'is',
  'Italian': 'it',
  'Japanese': 'ja',
  'Korean': 'ko',
  'Lithuanian': 'lt',
  'Latvian': 'lv',
  'Malagasy': 'mg',
  'Malay': 'ms',
  'Maltese': 'mt',
  'Hmong Daw': 'mww',
  'Norwegian': 'nb',
  'Dutch': 'nl',
  'Querétaro Otomi': 'otq',
  'Polish': 'pl',
  'Portuguese': 'pt',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Samoan': 'sm',
  'Serbian (Cyrillic)': 'sr-Cyrl',
  'Serbian (Latin)': 'sr-Latn',
  'Swedish': 'sv',
  'Kiswahili': 'sw',
  'Tamil': 'ta',
  'Telugu': 'te',
  'Thai': 'th',
  'Klingon': 'tlh',
  'Tongan': 'to',
  'Turkish': 'tr',
  'Tahitian': 'ty',
  'Ukrainian': 'uk',
  'Urdu': 'ur',
  'Vietnamese': 'vi',
  'Yucatec Maya': 'yua',
  'Cantonese (Traditional)': 'yue',
  'Chinese Simplified': 'zh-Hans',
  'Chinese Traditional': 'zh-Hant'
};

export var yandexLanguages = {
  Albanian: 'sq',
  Arabic: 'ar',
  Armenian: 'hy',
  Azeri: 'az',
  Belarusian: 'be',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Croatian: 'hr',
  Czech: 'cs',
  Chinese: 'zh',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Esperanto: 'eo',
  Estonian: 'et',
  Finnish: 'fi',
  French: 'fr',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Hindi:'hi',
  Hebrew: 'he',
  Hungarian: 'hu',
  Icelandic: 'is',
  Indonesian: 'id',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Macedonian: 'mk',
  Malay: 'ms',
  Maltese: 'mt',
  Norwegian: 'no',
  Polish: 'pl',
  Portuguese: 'pt',
  Romanian: 'ro',
  Russian: 'ru',
  Spanish: 'es',
  Serbian: 'sr',
  Slovak: 'sk',
  Slovenian: 'sl',
  Swedish: 'sv',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Vietnamese: 'vi'
};

export var googleLanguages = {
  'Afrikaans': 'af',
  'Albanian': 'sq',
  'Arabic': 'ar',
  'Armenian': 'hy',
  'Azerbaijani': 'az',
  'Basque': 'eu',
  'Belarusian': 'be',
  'Bengali': 'bn',
  'Bosnian': 'bs',
  'Bulgarian': 'bg',
  'Catalan': 'ca',
  'Cebuano': 'ceb',
  'Chichewa': 'ny',
  'Chinese Simplified': 'zh-CN',
  'Chinese Traditional': 'zh-TW',
  'Croatian': 'hr',
  'Czech': 'cs',
  'Danish': 'da',
  'Dutch': 'nl',
  'English': 'en',
  'Esperanto': 'eo',
  'Estonian': 'et',
  'Filipino': 'tl',
  'Finnish': 'fi',
  'French': 'fr',
  'Galician': 'gl',
  'Georgian': 'ka',
  'German': 'de',
  'Greek': 'el',
  'Gujarati': 'gu',
  'Haitian Creole': 'ht',
  'Hausa': 'ha',
  'Hebrew': 'iw',
  'Hindi': 'hi',
  'Hmong': 'hmn',
  'Hungarian': 'hu',
  'Icelandic': 'is',
  'Igbo': 'ig',
  'Indonesian': 'id',
  'Irish': 'ga',
  'Italian': 'it',
  'Japanese': 'ja',
  'Javanese': 'jw',
  'Kannada': 'kn',
  'Kazakh': 'kk',
  'Khmer': 'km',
  'Korean': 'ko',
  'Lao': 'lo',
  'Latin': 'la',
  'Latvian': 'lv',
  'Lithuanian': 'lt',
  'Macedonian': 'mk',
  'Malagasy': 'mg',
  'Malay': 'ms',
  'Malayalam': 'ml',
  'Maltese': 'mt',
  'Maori': 'mi',
  'Marathi': 'mr',
  'Mongolian': 'mn',
  'Myanmar (Burmese)': 'my',
  'Nepali': 'ne',
  'Norwegian': 'no',
  'Persian': 'fa',
  'Polish': 'pl',
  'Portuguese': 'pt',
  'Punjabi': 'ma',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Serbian': 'sr',
  'Sesotho': 'st',
  'Sinhala': 'si',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Somali': 'so',
  'Spanish': 'es',
  'Sudanese': 'su',
  'Swahili': 'sw',
  'Swedish': 'sv',
  'Tajik': 'tg',
  'Tamil': 'ta',
  'Telugu': 'te',
  'Thai': 'th',
  'Turkish': 'tr',
  'Ukrainian': 'uk',
  'Urdu': 'ur',
  'Uzbek': 'uz',
  'Vietnamese': 'vi',
  'Welsh': 'cy',
  'Yiddish': 'yi',
  'Yoruba': 'yo',
  'Zulu': 'zu'
};

export var webSpeechLanguages = {
  'af-ZA': 'Afrikaans',
  'id-ID': 'Bahasa Indonesia',
  'ms-MY': 'Bahasa Melayu',
  'ca-ES': 'Català',
  'cs-CZ': 'Čeština',
  'de-DE': 'Deutsch',
  'en-AU': 'English - Australia',
  'en-CA': 'English - Canada',
  'en-IN': 'English - India',
  'en-NZ': 'English - New Zealand',
  'en-ZA': 'English - South Africa',
  'en-GB': 'English - United Kingdom',
  'en-US': 'English - United States',
  'es-AR': 'Español - Argentina',
  'es-BO': 'Español - Bolivia',
  'es-CL': 'Español - Chile',
  'es-CO': 'Español - Colombia',
  'es-CR': 'Español - Costa Rica',
  'es-EC': 'Español - Ecuador',
  'es-SV': 'Español - El Salvador',
  'es-ES': 'Español - España',
  'es-US': 'Español - Estados Unidos',
  'es-GT': 'Español - Guatemala',
  'es-HN': 'Español - Honduras',
  'es-MX': 'Español - México',
  'es-NI': 'Español - Nicaragua',
  'es-PA': 'Español - Panamá',
  'es-PY': 'Español - Paraguay',
  'es-PE': 'Español - Perú',
  'es-PR': 'Español - Puerto Rico',
  'es-DO': 'Español - República Dominicana',
  'es-UY': 'Español - Uruguay',
  'es-VE': 'Español - Venezuela',
  'gu-IN': 'ગુજરાતી',
  'kn-IN': 'ಕನ್ನಡ',
  'km-KH': 'ភាសាខ្មែរ',
  'lv-LV': 'Latviešu',
  'lt-LT': 'Lietuvių',
  'ml-IN': 'മലയാളം',
  'mr-IN': 'मराठी',
  'hu-HU': 'Magyar',
  'lo-LA': 'ລາວ',
  'nl-NL': 'Nederlands',
  'ne-NP': 'नेपाली भाषा',
  'nb-NO': 'Norsk bokmål',
  'si-LK': 'සිංහල',
  'sl-SI': 'Slovenščina',
  'su-ID': 'Basa Sunda',
  'sw-TZ': 'Kiswahili - Tanzania',
  'sw-KE': 'Kiswahili - Kenya',
  'ka-GE': 'ქართული',
  'hy-AM': 'Հայերեն',
  'ta-IN': 'தமிழ் - இந்தியா',
  'ta-SG': 'தமிழ் - சிங்கப்பூர்',
  'ta-LK': 'தமிழ் - இலங்கை',
  'ta-MY': 'தமிழ் - மலேசியா',
  'te-IN': 'తెలుగు',
  'vi-VN': 'Tiếng Việt',
  'tr-TR': 'Türkçe',
  'ur-PK': 'اُردُو - پاکستان',
  'ur-IN': 'اُردُو - بھارت',
  'el-GR': 'Ελληνικά',
  'uk-UA': 'Українська',
  'hi-IN': 'हिन्दी',
  'th-TH': 'ภาษาไทย',
  'eu-ES': 'Euskara',
  'fr-FR': 'Français',
  'gl-ES': 'Galego',
  'hr_HR': 'Hrvatski',
  'zu-ZA': 'IsiZulu',
  'is-IS': 'Íslenska',
  'it-IT': 'Italiano-Italia',
  'it-CH': 'Italiano-Svizzera',
  'pl-PL': 'Polski',
  'pt-BR': 'Português-Brasil',
  'pt-PT': 'Português-Portugal',
  'ro-RO': 'Română',
  'sk-SK': 'Slovenčina',
  'fi-FI': 'Suomi',
  'sv-SE': 'Svenska',
  'bg-BG': 'български',
  'ru-RU': 'Pусский',
  'sr-RS': 'Српски',
  'ko-KR': '한국어',
  'cmn-Hans-CN': '中文 - 普通话 (中国大陆)',
  'cmn-Hans-HK': '中文 - 普通话 (香港)',
  'cmn-Hant-TW': '中文 - 中文 (台灣)',
  'yue-Hant-HK': '中文 - 粵語 (香港)',
  'ja-JP': '日本語',
  'la': 'Lingua latīna',
  'jv-ID': 'Basa Jawa',
  'fil-PH': 'Filipino'
};
