export var azureLanguages = {
  'Afrikaans': 'af',
  'Arabic': 'ar',
  'Bulgarian': 'bg',
  'Bangla': 'bn',
  'Bosnian': 'bs',
  'Catalan': 'ca',
  'Czech': 'cs',
  'Welsh': 'cy',
  'Danish': 'da',
  'German': 'de',
  'Greek': 'el',
  'English': 'en',
  'Spanish': 'es',
  'Estonian': 'et',
  'Persian': 'fa',
  'Finnish': 'fi',
  'Filipino': 'fil',
  'Fijian': 'fj',
  'French': 'fr',
  'Hebrew': 'he',
  'Hindi': 'hi',
  'Croatian': 'hr',
  'Haitian Creole': 'ht',
  'Hungarian': 'hu',
  'Indonesian': 'id',
  'Icelandic': 'is',
  'Italian': 'it',
  'Japanese': 'ja',
  'Korean': 'ko',
  'Lithuanian': 'lt',
  'Latvian': 'lv',
  'Malagasy': 'mg',
  'Malay': 'ms',
  'Maltese': 'mt',
  'Hmong Daw': 'mww',
  'Norwegian': 'nb',
  'Dutch': 'nl',
  'Querétaro Otomi': 'otq',
  'Polish': 'pl',
  'Portuguese': 'pt',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Samoan': 'sm',
  'Serbian (Cyrillic)': 'sr-Cyrl',
  'Serbian (Latin)': 'sr-Latn',
  'Swedish': 'sv',
  'Kiswahili': 'sw',
  'Tamil': 'ta',
  'Telugu': 'te',
  'Thai': 'th',
  'Klingon': 'tlh',
  'Tongan': 'to',
  'Turkish': 'tr',
  'Tahitian': 'ty',
  'Ukrainian': 'uk',
  'Urdu': 'ur',
  'Vietnamese': 'vi',
  'Yucatec Maya': 'yua',
  'Cantonese (Traditional)': 'yue',
  'Chinese Simplified': 'zh-Hans',
  'Chinese Traditional': 'zh-Hant'
};

export var yandexLanguages = {
  Albanian: 'sq',
  Arabic: 'ar',
  Armenian: 'hy',
  Azeri: 'az',
  Belarusian: 'be',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Croatian: 'hr',
  Czech: 'cs',
  Chinese: 'zh',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Esperanto: 'eo',
  Estonian: 'et',
  Finnish: 'fi',
  French: 'fr',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Hindi:'hi',
  Hebrew: 'he',
  Hungarian: 'hu',
  Icelandic: 'is',
  Indonesian: 'id',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Macedonian: 'mk',
  Malay: 'ms',
  Maltese: 'mt',
  Norwegian: 'no',
  Polish: 'pl',
  Portuguese: 'pt',
  Romanian: 'ro',
  Russian: 'ru',
  Spanish: 'es',
  Serbian: 'sr',
  Slovak: 'sk',
  Slovenian: 'sl',
  Swedish: 'sv',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Vietnamese: 'vi'
};

export var googleLanguages = {
  'Afrikaans': 'af',
  'Albanian': 'sq',
  'Arabic': 'ar',
  'Armenian': 'hy',
  'Azerbaijani': 'az',
  'Basque': 'eu',
  'Belarusian': 'be',
  'Bengali': 'bn',
  'Bosnian': 'bs',
  'Bulgarian': 'bg',
  'Catalan': 'ca',
  'Cebuano': 'ceb',
  'Chichewa': 'ny',
  'Chinese Simplified': 'zh-CN',
  'Chinese Traditional': 'zh-TW',
  'Croatian': 'hr',
  'Czech': 'cs',
  'Danish': 'da',
  'Dutch': 'nl',
  'English': 'en',
  'Esperanto': 'eo',
  'Estonian': 'et',
  'Filipino': 'tl',
  'Finnish': 'fi',
  'French': 'fr',
  'Galician': 'gl',
  'Georgian': 'ka',
  'German': 'de',
  'Greek': 'el',
  'Gujarati': 'gu',
  'Haitian Creole': 'ht',
  'Hausa': 'ha',
  'Hebrew': 'iw',
  'Hindi': 'hi',
  'Hmong': 'hmn',
  'Hungarian': 'hu',
  'Icelandic': 'is',
  'Igbo': 'ig',
  'Indonesian': 'id',
  'Irish': 'ga',
  'Italian': 'it',
  'Japanese': 'ja',
  'Javanese': 'jw',
  'Kannada': 'kn',
  'Kazakh': 'kk',
  'Khmer': 'km',
  'Korean': 'ko',
  'Lao': 'lo',
  'Latin': 'la',
  'Latvian': 'lv',
  'Lithuanian': 'lt',
  'Macedonian': 'mk',
  'Malagasy': 'mg',
  'Malay': 'ms',
  'Malayalam': 'ml',
  'Maltese': 'mt',
  'Maori': 'mi',
  'Marathi': 'mr',
  'Mongolian': 'mn',
  'Myanmar (Burmese)': 'my',
  'Nepali': 'ne',
  'Norwegian': 'no',
  'Persian': 'fa',
  'Polish': 'pl',
  'Portuguese': 'pt',
  'Punjabi': 'ma',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Serbian': 'sr',
  'Sesotho': 'st',
  'Sinhala': 'si',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Somali': 'so',
  'Spanish': 'es',
  'Sudanese': 'su',
  'Swahili': 'sw',
  'Swedish': 'sv',
  'Tajik': 'tg',
  'Tamil': 'ta',
  'Telugu': 'te',
  'Thai': 'th',
  'Turkish': 'tr',
  'Ukrainian': 'uk',
  'Urdu': 'ur',
  'Uzbek': 'uz',
  'Vietnamese': 'vi',
  'Welsh': 'cy',
  'Yiddish': 'yi',
  'Yoruba': 'yo',
  'Zulu': 'zu'
};
